spring:
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  thymeleaf:
    cache: false
    prefix: classpath:/static/
#QQ邮箱配置
  mail:
    host: smtp.qq.com
    username: 1390836670@qq.com
    password: upwcekoxlxjogehc
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: wcfb.model.po
mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: wcfb.model.po
logging:
  file:
    path: E:\other\appData\comment\log
  level:
    wcfb: warn